### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [xdid-net/facebookpixel#1]
https://github.com/xdid-net/facebookpixel/blob/d2f161b6a12d3f0c01b545808d86e9ec2cfdc671/template.tpl#L54

When reviewing your template, we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [encodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by xdid-net** [comment]
Fixed with new version
